### ISSUE TITLE
supersearchfacet errors out with columns that don't exist or that you don't have access to

### ISSUE THREAD

**Issue by willkg** [willkg/crashstats-tools#62]
`supersearchfacet` errors out when you specify a column you don't have access to (maybe you forgot your token).

```
$ supersearchfacet --_facets=gmp_library_path
Traceback (most recent call last):
  File "/home/willkg/.local/bin/supersearchfacet", line 33, in <module>
    sys.exit(load_entry_point('crashstats-tools', 'console_scripts', 'supersearchfacet')())
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/willkg/mozilla/crashstats-tools/src/crashstats_tools/cmd_supersearchfacet.py", line 316, in supersearchfacet
    for column in headers:
UnboundLocalError: local variable 'headers' referenced before assignment
```

```
$ supersearchfacet --_facets=foo
Traceback (most recent call last):
  File "/home/willkg/.local/bin/supersearchfacet", line 33, in <module>
    sys.exit(load_entry_point('crashstats-tools', 'console_scripts', 'supersearchfacet')())
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/willkg/.local/pipx/venvs/crashstats-tools/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/willkg/mozilla/crashstats-tools/src/crashstats_tools/cmd_supersearchfacet.py", line 316, in supersearchfacet
    for column in headers:
UnboundLocalError: local variable 'headers' referenced before assignment
```

**Comment by willkg** [comment]
I'm pretty sure this was fixed in e3516ba6. At a minimum, I can't reproduce it anymore.
